config/routes.rb
Rails.application.routes.draw do
  
  root 'batches#home'

  resources :attendances

  devise_for :teachers


  # get 'students/create'
  post 'students/create', as: :students
  # get 'students/destroy'
  delete 'students/:id', to: 'students#destroy', as: :destroy_student


# changing the get request to post and adding as for path
  post 'batches/create', as: :batches
# get 'batches/destroy' changing destroy path
  delete 'batches/:id', to: 'batches#destroy', as: :destroy_batch


   # get 'classdays/create'
  post 'classdays/create', as: :classdays
  # get 'classdays/destroy'
  delete 'classdays/:id', to: 'classdays#destroy', as: :destroy_classday


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :classday
  belongs_to :student
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :teacher
  has_many :students
  has_many :classdays
end

app/models/classday.rb
class Classday < ApplicationRecord
  belongs_to :batch
  has_many :attendances
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :batch
  belongs_to :teacher
  has_many :attendances
  has_many :classdays, through: :attendances

end

app/models/teacher.rb
class Teacher < ApplicationRecord
	has_many :batches
	has_many :students


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController


	# Here, qr code will set the classday_id and present to current class's id and yes respectively.

	def index
		@qr = RQRCode::QRCode.new( render :"", :size => 4, :level => :h ) # after qr code is scanned, redirect to root
    end

    DEF ATTENDANCE FORM
    	
    end
  


end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  
  before_action :authenticate_teacher!, only: [:create, :destroy]
  before_action :set_batch, only: [:destroy]
  before_action :authorize_teacher, only: [:destroy]


  def home
  	@batch = Batch.new
    @batches = Batch.all
    @new_student = Student.new
    @classday = Classday.new
    @attendance = Attendance.new
  end

  def create	
  	@batch = Batch.create(name: params[:batch][:name], teacher_id:current_teacher.id)

  	redirect_to root_path
  end

  def destroy
  	@x.destroy
  	redirect_to root_path
  end

     private

   def set_batch
   	@x = Batch.find(params[:id])
   end

   def authorize_teacher
   	if current_teacher.id != @x.teacher_id
   		redirect_to action: 'home'
   	end
  	
   end


end

app/controllers/classdays_controller.rb
class ClassdaysController < ApplicationController
  
  def create
  	@classday = Classday.create(date: params[:classday][:date], batch_id: params[:classday][:batch_id])
  	redirect_to root_path
  end

  def destroy
  	Classday.find_by(params[:id]).destroy
  	redirect_to root_path
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  before_action :authenticate_teacher!, only: [:create, :destroy]
  before_action :set_student, only: [:destroy]
  before_action :authorize_teacher, only: [:destroy]

  def create
  	@new_student = Student.create(name: params[:student][:name], teacher_id: current_teacher.id, batch_id: params[:student][:batch_id])
  	redirect_to root_path
  end

  def destroy
  	@x.destroy
  	redirect_to root_path
  end

  private

  def set_student
  	@x = Student.find(params[:id])  	
  end

  def authorize_teacher
  	if current_teacher.id != @x.teacher_id
  	   redirect_to root_path
    end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/classdays_helper.rb
module ClassdaysHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/attendances/index.html.erb
<h1>Scan this code and enter student_id given to you!</h1>

<%= raw @qr.as_html %>

app/views/batches/_attend.html.erb
<h1>enter your student_id</h1>

<%= form_for @attendance do |a| %>
<%= a.hidden_field :classday_id, value: c.id %>
<%= a.hidden_field :present, value: 'yes' %>
<%= a.label :student_id %>
<%= a.text_area :student_id %>
<%= a.submit %>
<% end %>

app/views/batches/create.html.erb
<h1>Batches#create</h1>
<p>Find me in app/views/batches/create.html.erb</p>

app/views/batches/destroy.html.erb
<h1>Batches#destroy</h1>
<p>Find me in app/views/batches/destroy.html.erb</p>

app/views/batches/home.html.erb
<!-- <h1>Batches#home</h1>
<p>Find me in app/views/batches/home.html.erb</p> -->

-----Add a new batch----
<div id="new-batch-form">
	<%= form_for @batch do |b| %>
	<%= b.label :name %>
	<%= b.text_area :name %>
	<%= b.submit %>
	<% end %>
</div>

<div id="batch-list">
	<ul>
		<div id="container">
			
		 <% @batches.reverse.each do |b| %>
		  
		 <li> 
		  	<%= b.name %> | <%= b.teacher.email %>
		  	<% if teacher_signed_in? && b.teacher_id == current_teacher.id %>
		  	<%= link_to 'Delete', destroy_batch_path(b.id), method: :delete %>
		  	<% end %> 

		  <div id="students-list">
		  	<ul>
		  		<% b.students.reverse.each do |s| %>
		  		<li> <%= s.name %> </li>
		  		<% end %>
		  	</ul>
		  	
		  	-----Add a new student to batch----
		  	<% if teacher_signed_in? %>
		  	<div id="new-student-form">
		  		<%= form_for @new_student do |s| %>
		  		<%= s.label :name %>
		  		<%= s.text_area :name %>
		  		<%= s.hidden_field :batch_id, value: b.id %>
		  		<%= s.submit %>
		  		<% end %>		  		
		  	</div>
		  	<% end %>

		  </div>

		  
		  <div id="classdays-list">

		  	<ul>
		  	   <% b.classdays.reverse.each do |c| %>
		  	   ----classdays with attendance list here---
		  	   
		  	   <li> 
		  	   	<%= c.date %> | <%= link_to 'Mark attendance', controller :, method: :get %>
		  	   	<ul>
		  	   		<% c.attendances.each do |a| %>
		  	   		<li> <%= a.student_id %> </li>
		  	   	    <% end %>
		  	   	</ul>
		  	   </li>

		  	   <% end %>
		    </ul>
		    
		    -----Add a new classday to batch----
		  	<% if teacher_signed_in? %>
		  	<div id="new-classday-form">
		  		<%= form_for @classday do |c| %>
		  		<%= c.hidden_field :batch_id, value: b.id %>
		  		<%= c.label :date %>
		  		<%= c.text_area :date %>
		  		<%= c.submit %>
		  		<% end %>		  		
		  	</div>
		  	<% end %>
		    	
		    </div>

		  </div>

		 </li>
 
		 <% end %>

		</div>
		
	</ul>
	
</div>

app/views/classdays/create.html.erb
<h1>Classdays#create</h1>
<p>Find me in app/views/classdays/create.html.erb</p>

app/views/classdays/destroy.html.erb
<h1>Classdays#destroy</h1>
<p>Find me in app/views/classdays/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SCANit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <div class = "auth-info-links">
      
     <% if teacher_signed_in? %>
       
       <div id="sign-in-up">
         <div> <%= current_teacher.email %> </div>
         <div class="box"> <%= link_to 'Sign Out', destroy_teacher_session_path, method: :delete %> </div>
       </div><hr>

     <% else %>

       <div id="sign-in-up">
         <div class="box"> <%= link_to 'Sign In', new_teacher_session_path %> </div>
         <div class="box"> <%= link_to 'Sign Up', new_teacher_registration_path %> </div>
       </div> <hr>
     <% end %>

    </div>

    <%= yield %>
  </body>
</html>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>